### PR TITLE
Lukas thief steal

### PR DESCRIPTION
**Pull request by Tacitor**
The thief steals cards now. Next, I will add the player to choose which cards get stolen.

### CODE REVIEW

**Comment by Tacitor** [comment]
Pushing some code that I don't want to get merged just yet.

**Comment by Tacitor** [comment]
Done

**Comment by Tacitor** [comment]
I also moved the Image variables to the ImageRef class. Still, works the same though because of the public static variables

**Review by Tacitor — COMMENTED** [review]
All good

**Review by Tacitor — COMMENTED** [review]
Delete the branch when merged.

**Review by Evan-Kreutzwiser — APPROVED** [review]
I haven't looked over *all* of the code, but i pulled and tested the stealing and it works correctly.

It took a bit to get used to all of the turn switching involved

**Pull request merged**
